# kubectl apply -f 31-configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration-x01
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  disable-access-log: 'false'
  worker-processes: '1'
  use-proxy-protocol: 'true'
  enable-syslog: 'false'
  #syslog-host: rsyslog-nginx-svc.logs-k8s3.svc
  #syslog-port: '5140'
  max-worker-connections: '65536'
  proxy-body-size: 20m
  proxy-connect-timeout: '10'
  server-tokens: 'false'
  ssl-redirect: 'false'
  use-geoip: 'false'
  use-geoip2: 'true'
  worker-cpu-affinity: auto
  allow-backend-server-header: 'true'
  #compute-full-forwarded-for: 'true'
  use-forwarded-headers: 'true'
  #forwarded-for-header: X-Forwarded-For
  enable-underscores-in-headers: 'true'
  generate-request-id: 'true'
  ignore-invalid-headers: 'true'
  #proxy-stream-timeout: 75s
  log-format-escape-json: 'true'
  log-format-upstream:
    '{"@timestamp":"$time_iso8601",
    "remote_addr":"$remote_addr",
    "xff":"$http_x_forwarded_for",
    "user_agent":"$http_user_agent",
    "session_id":"$cookie_o_account",
    "referer":"$http_referer",
    "scheme":"$scheme",
    "domain":"$host",
    "uri":"$uri",
    "request_uri":"$request_uri",
    "request_method":"$request_method",
    "request_length":"$request_length",
    "request_time":"$request_time",
    "req_id":"$req_id",
    "upstream_addr":"$upstream_addr",
    "upstream_time":"$upstream_response_time",
    "status":"$status",
    "size":"$body_bytes_sent",
    "geoip":{
      "ip":"$remote_addr",
      "country_code":"$geoip2_city_country_code",
      "country_name":"$geoip2_city_country_name",
      "region_code":"$geoip2_region_code",
      "region_name":"$geoip2_region_name",
      "city_name":"$geoip2_city",
      "location":{
        "lat":"$geoip2_latitude",
        "lon":"$geoip2_longitude",
      }
    },
    "ingress":"$hostname",
    "namespace":"$namespace",
    "ingress_name":"$ingress_name",
    "service_name":"$service_name"}'

