# 用于进行负载穿透，向外部暴露本机对应的端口
# kubectl apply -f 41-klipper-hk42.yaml
kind: Pod
apiVersion: v1
metadata:
  name: ingress-nodeport-hk42
  namespace: ingress-nginx
spec:
  nodeSelector:
    kubernetes.io/os: linux
    k3s.io/internal-ip: 10.147.20.42
  containers:
    - name: lb-port-80
      image: 'rancher/klipper-lb:v0.1.2'
      imagePullPolicy: IfNotPresent
      ports:
        - name: lb-port-80
          hostPort: 80
          containerPort: 80
          protocol: TCP
      env:
        - name: SRC_PORT
          value: '80'
        - name: DEST_PROTO
          value: TCP
        - name: DEST_PORT
          value: '30080'
        - name: DEST_IP
          value: 10.147.20.42
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
    - name: lb-port-443
      image: 'rancher/klipper-lb:v0.1.2'
      imagePullPolicy: IfNotPresent
      ports:
        - name: lb-port-443
          hostPort: 443
          containerPort: 443
          protocol: TCP
      env:
        - name: SRC_PORT
          value: '443'
        - name: DEST_PROTO
          value: TCP
        - name: DEST_PORT
          value: '30442'
        - name: DEST_IP
          value: 10.147.20.42
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
